[package]
name = "craneliftc"
version = "0.5.1"
edition = "2021"
description = "light c compatible ffi wrapper around cranelift"
license-file = "LICENSE"
readme = "README.md"

[dependencies]
cranelift = "0"
paste = "1.0.11"

