name: cd
on:
  push:
    branches:
      - main
jobs:
  crate-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: |
          cargo +nightly package
          cargo +nightly publish -p craneliftc --token ${{ secrets.CARGO_TOKEN }}
