name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  lint-craneliftc:
    runs-on: ubuntu-latest
    environment: secret
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
      - run: |
          rustup component add rustfmt --toolchain nightly
          cargo +nightly install cbindgen --force
          cargo +nightly build
          cargo +nightly test
          cargo +nightly fmt --all -- --check
          cbindgen --config cbindgen.toml --crate craneliftc --output ./headers/craneliftc.h
          git diff --quiet
